# from redBlackTree import *
# rbt = RedBlackTree()
# rbt.insertRBT(145)
# rbt.insertRBT(98)
# rbt.insertRBT(45)
# rbt.insertRBT(32)
# rbt.levelorderDisplay()
# rbt.insertRBT(18)
# rbt.levelorderDisplay()
# rbt = RedBlackTree()
# rbt.insertRBT(145)
# rbt.insertRBT(98)
# rbt.insertRBT(45)
# # rbt.insertRBT(5)
# # rbt.insertRBT(4)
# # rbt.insertRBT(3)
# # rbt.insertRBT(2)
# # rbt.insertRBT(1)
# # rbt.inorderDisplay()
# rbt.levelorderDisplay()
# from AVLBinaryTree import *
# avl = AVLTree()
# avl.insertAVL(198)
# avl.insertAVL(95)
# avl.insertAVL(228)
# avl.insertAVL(205)
# avl.insertAVL(145)
# avl.insertAVL(73)
# # avl.levelorderDisplay()
# avl.deleteInAVL(198)
# avl.deleteInAVL(205)
# avl.deleteInAVL(228)
# avl.deleteInAVL(95)
# avl.deleteInAVL(73)
# avl.deleteInAVL(145)
# # avl.rightRotate()
# avl.inorderDisplay()
from binarySearchTree import *
bst = BinarySearchTree()
bst.insertBST(125)
# bst.delteINBST(45)
bst.insertBST(46)
bst.insertBST(98)
bst.insertBST(106)
bst.insertBST(135)
bst.insertBST(181)
bst.insertBST(212)
bst.insertBST(256)
bst.insertBST(272)
bst.insertBST(316)
bst.insertBST(352)
# bst.insertBST(368)
# bst.insertBST(396)
# bst.insertBST(418)
# bst.insertBST(516)
# bst.insertBST(48)
# bst.insertBST(162)
# bst.insertBST(54)
# bst.insertBST(36)
# bst.insertBST(99)
# bst.searchBST(45)
# bst.delteINBST(125)
# bst.delteINBST(99)
# bst.delteINBST(54)
# bst.delteINBST(48)
# bst.delteINBST(46)
# bst.delteINBST(162)
# bst.delteINBST(36)
# bst.delteINBST(199)
# print("AFTER DELETION")
bst.inorderDisplay()
print()
bst.inorderDisplayR()
print()
# bst.preorderDisplay()
# print()
# bst.postorderDisplay()
# print()
# bst.levelorderDisplay()
# bst.deletBST()
# from binaryTree import *
# bt = BinaryTree()
# bt.createBT(45)
# bt.insertBT(1258)
# bt.insertBT(194)
# bt.insertBT(123)
# bt.insertBT(98)
# bt.insertBT(29)
# bt.insertBT(56)
# bt.inorderDisplay()
# bt.preorderDisplay()
# bt.postorderDisplay()
# bt.levelorderDisplay()
# bt.deleteInBT(123)
# bt.deleteInBT(56)
# bt.deleteInBT(98)
# bt.inorderDisplay()
# bt.preorderDisplay()
# bt.postorderDisplay()
# bt.levelorderDisplay()
# bt.deleteInBT()
# bt.deleteBT()
# bt.levelorderDisplay()
