from queueUsingLL import *
queue = Queue()
queue.display()
queue.dequeue()
queue.frontele()
queue.rearele()
queue.length()
queue.enqueue(154)
queue.enqueue(1846)
queue.enqueue(1231)
queue.enqueue(45)
queue.enqueue(98)
queue.display()
queue.frontele()
queue.rearele()
queue.dequeue()
queue.frontele()
queue.rearele()
queue.display()
queue.dequeue()
queue.frontele()
queue.rearele()
queue.display()
queue.length()
queue.frontele()
queue.rearele()
queue.delete()
queue.frontele()

# from stackUsingLL import *
# stack = Stack()
# stack.display()
# stack.peek()
# stack.pop()
# stack.display()
# stack.push(45)
# stack.display()
# stack.push(128)
# print(stack.length())
# stack.push(3)
# stack.push(845)
# stack.display()
# print(stack.pop())
# print(stack.peek())
# print(stack.pop())
# print(stack.peek())
# print(stack.length())
# stack.display()
# stack.delete()
# stack.display()