# from singlell import *
from circulardoubleLL import *
CDLL = CircularDoubleLinkedList()
CDLL.createCDLL(45)
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.rev_displayCDLL()
CDLL.insertCDLL(23)
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.insertCDLL(198)
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.insertCDLL(2)
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.insertCDLL(598,0)
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.insertCDLL(597,45)
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.insertCDLL(598,4)
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.searchCDLL(198)
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.searchCDLL(597)
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.searchCDLL(145)
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.deleteInCDLL()
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.deleteInCDLL(0)
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.deleteInCDLL(98)
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.deleteInCDLL(3)
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.deleteInCDLL()
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.deleteInCDLL()
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.deleteInCDLL()
CDLL.display()
CDLL.rev_displayCDLL()
CDLL.deleteInCDLL()
CDLL.display()
CDLL.rev_displayCDLL()
# # from singlell import *
# from circularsingleLL import *
# CLL = circularsingleLL()
# CLL.createCLL(45)
# CLL.display()
# CLL.insertCLL(23)
# CLL.display()
# CLL.insertCLL(198)
# CLL.display()
# CLL.insertCLL(2)
# CLL.display()
# CLL.insertCLL(598,0)
# CLL.display()
# CLL.insertCLL(597,45)
# CLL.display()
# CLL.insertCLL(598,4)
# CLL.display()
# CLL.searchCLL(198)
# CLL.display()
# CLL.searchCLL(597)
# CLL.display()
# CLL.searchCLL(145)
# CLL.display()
# CLL.deleteInCLL()
# CLL.display()
# CLL.deleteInCLL(0)
# CLL.display()
# CLL.deleteInCLL(98)
# CLL.display()
# CLL.deleteInCLL(3)
# CLL.display()
# CLL.deleteInCLL()
# CLL.display()
# CLL.deleteInCLL()
# CLL.display()
# CLL.deleteInCLL()
# CLL.display()
# CLL.deleteInCLL()
# CLL.display()

